tsenart/vegeta

- README.md
> REAME > Install Vegeta via Homebrew

- README.md
> Swap "of need" to "of a need" in README

- lib/reporters.go
- lib/reporters_test.go
> reporter: Improve histogram flag parser

- .travis.yml
- README.md
- attack.go
- lib/attack.go
- lib/attack_test.go
- lib/metrics.go
- lib/metrics_test.go
- lib/reporters.go
- main.go
This change set substantially improves the performance of Vegeta attacks and allows it to drive much higher request rates than before.
Fixes #120
> Attacker performance improvements

- attack.go
- attack_test.go
> Allow case-sensitive headers.

- README.md
> Document -reporter=plot

- attack.go
- flags.go
> Add support for TLS client certs

- README.md
> Correct LICENSE link on README.md

- lib/reporters.go
- lib/reporters_test.go
- report.go
> Parameterise plot title in NewPlotReporter

- lib/results.go
Reading your code as I am picking up go. I like the overall design so far.
> Doc fix: Results -> Result type elements

- README.md
> Add jplot integration usage example to the README

- lib/reporters.go
> Add meta charset=utf-8 tag in plot reporter HTML output

- README.md
The quoting made the for loop iterate only once.
> README: Fix quoting in for loop.

- README.md
On e.g. Ubuntu, pdsh defaults to rsh; the user probably wants SSH here.
> README: Set pdsh to ssh mode

- Gopkg.lock
- Gopkg.toml
- lib/results.go
- lib/results_easyjson.go
- lib/results_test.go
- lib/targets.go
- lib/targets_easyjson.go
- lib/targets_test.go
It's much faster.
```
benchmark                            old ns/op     new ns/op     delta
BenchmarkEncodings/gob-encode-8      1278          1146          -10.33%
BenchmarkEncodings/gob-decode-8      131           128           -2.29%
BenchmarkEncodings/csv-encode-8      800           757           -5.38%
BenchmarkEncodings/csv-decode-8      705           657           -6.81%
BenchmarkEncodings/json-encode-8     2617          1212          -53.69%
BenchmarkEncodings/json-decode-8     6259          1547          -75.28%
benchmark                            old allocs     new allocs     delta
BenchmarkEncodings/gob-encode-8      2              2              +0.00%
BenchmarkEncodings/gob-decode-8      0              0              +0.00%
BenchmarkEncodings/csv-encode-8      2 …
```
> Use github.com/mailru/easyjson for JSON encoding and decoding of Targets and Results

- lib/attack.go
- lib/attack_test.go
Temp solution for #263 whilst #305 is under development
- [/] Git commit messages conform to [community standards](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [/] Each Git commit represents meaningful milestones or atomic units of work.
- [/] Changed or added code is covered by appropriate tests.
> Feature (library): BYO client and dialer

- README.md
> README: Fix -target section documentation

- README.md
Fixes https://github.com/tsenart/vegeta/issues/293#issuecomment-448281840
> Improve text report documentation

- README.md
- lib/targets.go
- lib/targets_test.go
> Enable to skip line including comments

- README.md
> README: Document target generation use-case

- lib/attack.go
- lib/attack_test.go
> attack: Measure latency when requests timeout

- README.md
> Minor grammar correction in readme

- lib/pacer.go
- lib/pacer_test.go
This commit extends the Pacer interface with a Rate method that returns
the instantaneous hit rate (per second) at a given point in time.
Fixes #476
> pacer: Extend interface with Rate method

- README.md
- attack.go
- encode.go
- file.go
- flags.go
- go.mod
- internal/cmd/jsonschema/main.go
- lib/plot/assets_gen.go
- lib/plot/plot.go
- lib/plot/plot_test.go
- lib/plot/timeseries.go
- plot.go
- report.go
https://github.com/tsenart/vegeta/issues/497
> fix: fix module import path for Go module

- README.md
> README: change go get to go install

- go.mod
- go.sum
fix [#595](https://github.com/tsenart/vegeta/issues/595)
relate PR: https://github.com/streadway/quantile/pull/8
> fix issue#595

- README.md
> README: Fix install from source instructions
