lib/attack.go

With chunked encoding, an HTTP server sends the response headers right
away and then streams the body chunks which can be lazily generated.
Without chunked encoding, network transfer time of the body wasn't
previously being accounted for.
Fixes #113

Always read response body for each hit

---

lib/metrics.go
lib/metrics_test.go

This change implements R's 8th type of quantile estimation which is
approximately median-unbiased regardless of the data distribution.
Fixes #129  /cc @alexeyrodriguez

Use R's 8th method of quantile estimation for latencies

---

lib/targets.go
lib/targets_test.go

Fixes #138 and allows several empty lines between targets.

Allow empty lines between targets

---

attack.go
lib/attack.go
lib/attack_test.go

This PR enables vegeta to run for indeterminate time until no more targets can be read or when explicitly stopped.
Fixes #149

Infinite attack

---

README.md
attack.go

This commit adds a flag to ignore invalid server TLS certificates.
/cc @aidylewis

attack: Implement -insecure flag

---

README.md

- `go install github.com/tsenart/vegeta` is not needed because `go get` already performs an install.
- Add `-u` flag to `go get` to ensure that the latest version is installed.

README: simplify Installing -> Source commands

---

lib/targets.go

Fixes #191.  Based on solution in #124.

Made headers in target definitions retain case sensitivity

---

lib/targets.go
lib/targets_test.go

The motivation and context for this PR are detailed in the proposal issue: https://github.com/tsenart/vegeta/issues/214
The implementation has changes as per maintainer's suggestions:
- with this PR vegeta now supports any upper-case ASCII word as a valid HTTP verb, not just  POST/GET/PUT/PATCH/DETELE/HEAD/OPTIONS...
CC @tsenart

PTAL allow any upper-case ASCII word to be an http method

---

lib/attack.go
lib/attack_test.go

Vegeta does not mark responses as success when `-1` is set to the attack `-redirects` option. `Bytes In`, `Bytes Out`, `Success` and `Status Codes` of a report are zeros as below:
```shell
echo "GET http://xxxx.xxxx" | vegeta attack -redirects -1 -rate 1 -duration 10s | tee results.bin | vegeta report
Requests      [total, rate]            10, 1.11
Duration      [total, attack, wait]    9.003078071s, 8.999999898s, 3.078173ms
Latencies     [mean, 50, 95, 99, max]  12.427662ms, 3.246776ms, 3.823605ms, 3.823605ms, 96.816248ms
Bytes In      [total, mean]            0, 0.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  0.00%
Status Codes  [code:count]             0:10
Error Set:
```
Have `a.client.CheckRedirect` return `http.ErrUseLastResponse` when `-1` …

mark responses as success in no redirect following mode.

---

lib/targets_test.go

This PR makes the error messages from this test have the same (right) spelling of a word.

[trivial] Typo in test failure message

---

attack.go
lib/attack.go

Hi,
It's my first PR here, and first in golang. ;) Thank you very much for your hard work on this project.
Probably support for h2c might be done better, so any suggestions welcome.

Addedd support for h2c requests (HTTP/2 without TLS)

---

lib/attack.go

Currently an `Attacker` sets the `Proxy` field to `http.ProxyFromEnvironment` which uses a proxy if the environment variables are present. This means there is no way to use a proxy only for a _specific_ attacker -- it's global. 
This change adds the ability to override the proxy settings on an `Attacker` instance.

Add option to override HTTP Proxy on Attacker.

---

Gopkg.lock
Makefile
README.md
attack.go
internal/cmd/jsonschema/main.go
lib/target.schema.json
lib/targets.go
lib/targets_test.go

The original targets format closely resembles plain HTTP/1.x messages. It was meant to be used by humans writing those targets directly on their terminals. With its lack of support for in-line body definitions, this ill-defined legacy format made Vegeta hard to integrate with other programs generating dynamic targets on the fly with distinct request bodies.
Extending the legacy format to support arbitrary in-line request bodies would require further deviation from the HTTP/1.x message format since, to the best of my knowledge, there is no official plain text framing format that would allow the boundaries between multiple targets with arbitrary request bodies to be easily recognized (and hence, parsed).
It could be done, certainly, but for the use case of integrating Vegeta with other …

JSON targets format

---

lib/metrics.go

To avoid long lines and easier readability in general.

metrics: Unindent types

---

README.md

Having two projects in one (mono) repo without separate versioning namespaces has led to breaking changes in one to affect the semantic versioning of both unintentionally. In order to isolate the signaling of breaking changes in each component, we're introducing versioning namespaces.
- `lib-vMAJOR.MINOR.PATCH` for library versions
- `cli-vMAJOR.MINOR.PATCH` for CLI versions
Henceforth, the two have versions that progress independently.

README: Document semantic versioning split

---

Gopkg.lock
Gopkg.toml
lib/metrics.go
lib/metrics_test.go

Benchmarking the current generation of streaming quantile libraries in Go has revealed https://github.com/influxdata/tdigest as the winner in performance without sacrificing expected levels of accuracy for the common quantiles. With this library, the 50th percentile is the one that may be less precise among all.
After this is merged, we can follow up with https://github.com/tsenart/vegeta/pull/268

metrics: Adopt T-Digest for streaming quantile estimation

---

attack.go
flags.go
lib/attack.go
lib/attack_test.go

This commit introduces vegeta.Rate which allows for the specification of
request rates with different time units than 1s.
Fixes #233

attack: Introduce flexible vegeta.Rate

---

README.md
encode.go
file.go
lib/results.go
lib/results_test.go
main.go
plot.go
report.go

With the goal to improve UX of the vegeta toolchain, this change aligns the behaviour of the `report`, `encode` and `plot` commands so that they can all read multiple input files of different encodings.
Fixes #255

Consistent multiple file argument handling across plot, report and encode.

---

Gopkg.lock
Gopkg.toml
README.md
attack.go
flags.go
lib/attack.go
lib/attack_test.go

This change set introduces a `-max-body` flag in the attack command
as well as the corresponding `vegeta.MaxBody` functional option to
use with `vegeta.NewAttacker`.
Fixes #325

attack: Support response body read limits

---

README.md
attack.go
lib/attack.go

PR #326 introduced a way to limit the number of bytes read from HTTP responses.
However, as pointed out by @smartyjohn in #302 (comment), it didn't solve the need
of reading all the response bodies (in order to observe the full network latency timing)
but discard them at the end.
This was an oversight and unintentional, so this change set changes the semantics
of both the `-max-body` flag in the `attack` command and the correspondent
`vegeta.MaxBody` `Attacker` option.
Instead of limiting the number of bytes **read** from the response bodies,
it limits the number of bytes **captured** from response bodies while
always reading the full body from the underlying connection.
Fixes #339

attack: Read response bodies in full

---

.travis.yml
lib/reporters.go
report.go
report_nonwindows.go
report_windows.go

This commit introduces the `--every` flag in the report command which
enables reports to be written out at specified interval. This allows
inspection of results as attacks are happening, instead of after they
finish.
Fixes #345

report: Implement --every flag for live updates

---

README.md

As reported in #357, only tags of the format `vMAJOR.MINOR.PATCH` are
supported by `go mod`. This change set documents how we'll create tags
in that format for library versions which will point to the same ref as
the `lib/vMAJOR.MINOR.PATCH` tags.
Fixes #357

Make git tag naming scheme compatible with `go mod`

---

README.md

In the Readme is stated that the number of CPUs used defaults to 8 which isn't correct, see: https://github.com/tsenart/vegeta/blob/0cabfc957a3db953c27ffaccff3ac2327a0dbcde/main.go#L24
BTW: is the commit message okay or how should I name it?

docs(cpus): correct default of CPUs usage

---

README.md
attack.go
lib/attack.go
lib/attack_test.go

We use a few HTTP services that are exposed over a unix socket rather than TCP, Go's support for this is good  and is used in several projects (e.g. Docker)  and would like to use vegeta for load testing them. 
This commit adds a `--unix-socket /path/to/unix.sock` option that sets the dialler on the request to a dialler for that unix socket. 
- [X ] Git commit messages conform to [community standards](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [X ] Each Git commit represents meaningful milestones or atomic units of work.
- [X ] Changed or added code is covered by appropriate tests.

Add unix sockets

---

.goreleaser.yml

To run inside a raspberry pi, the source code needs to be compiled for arm 32bits.
Tested on a raspberry pi 3b+ with the `HypriotOS/armv7` distro.
Are you able to provide the pre-compiled executable for ARM32 as well?
Thanks

Add ARM 32bits architecture

---

main.go

Previously some was printed to stderr, some was printed to stdout.
This caused the help text to be garbled sometimes, e.g. in certain terminals. Before fix:
After fix:
(Actually I first noticed this when running vegeta on a remote system using something like [fabric](http://www.fabfile.org/), where stdout and stderr are captured separately and returned as two strings, so any interleaving gets lost.)

main: Bugfix: Print all command line help text to stderr, not stdout

---

attack.go
lib/attack.go
lib/pacer.go
lib/pacer_test.go

@tsenart @LasTshaMAN
Supersedes #380, #388, #390.
I wanted to be able to vary attack rates over time, for Reasons. 
The Pacer interface allows vegeta's attack rate to be customized. Attack code keeps track of the elapsed attack duration and the number of hits sent and provides these to Pace, which must return a Duration
for the attack code to sleep for before sending the next hit. Pace may also return true for the second stop value to terminate the attack.
This interface allows vegeta to model a wider range of attack scenarios, such as diurnal request patterns or load-test behaviour, where the attack rate increases until the target begins to serve errors.
The change is primarily structured so that code using the vegeta lib will continue to function as before.
- [✔] Git commit messages …

Introduce Pacer interface, ConstantPacer and SinePacer.

---

README.md
internal/cmd/echosrv/main.go
lib/metrics.go
lib/metrics_test.go
lib/reporters.go

This commit adds a `Throughput` field to the `Metrics` struct which
represents the rate of successful requests per second. It is calculated
by dividing the number of successful requests by the time span in
seconds starting from the beginning of the earliest request in the
result set and ending in the time the very last response arrived.

metrics: Add Throughput to Metrics

---

README.md
attack.go
lib/attack.go

This PR introduces the `-max-workers` flag and associated function
options. This allows controlling the concurrency level that vegeta uses,
but can sacrifice reaching the requested `-rate`, in case the specified
max number of workers is below the what is needed to sustain such rate.

attack: Add -max-workers flag

---

README.md
attack.go
flags.go
internal/cmd/echosrv/main.go
lib/pacer.go
lib/pacer_test.go

This commit allows setting a zero rate which, together with a reasonable
number of `-max-workers`, behaves as independent concurrent users, each
sending a request and waiting for the response before sending the next
one.
This is part of enabling vegeta to work with the Universal Scalability
Law model, where a concurrency unit is defined as an independent
thread/worker/driver as described above (i.e. with backpressure).
Fixes #378

attack: Benchmarking with -rate=0 and -max-workers=N

---

lib/pacer.go
lib/pacer_test.go

This commit introduces a LinearPacer which paces an attack by starting
at a given request rate and increasing linearly with the given slope.
This is a pre-requisite for implementing #418

pacer: Introduce LinearPacer

---

README.md
attack.go
lib/attack.go
main.go

This PR adds support for proxy CONNECT headers. This allows sending custom headers to the proxy using the `-proxy-header` flag. Multiple headers can be sent by reusing the flag. Fixes https://github.com/tsenart/vegeta/issues/416
Example:
```
export HTTPS_PROXY=http://localhost:12345
./vegeta attack -duration=1s -insecure -targets=targets.txt -proxy-headers "Header1:Key1" -proxy-headers "Header2:key2"
[tmp] nc -lv 12345
CONNECT www.example.com:443 HTTP/1.1
Host: www.example.com:443
User-Agent: Go-http-client/1.1
Header1: Key1
Header2: key2

Support HTTP CONNECT proxy headers

---

README.md
attack.go
internal/cmd/echosrv/main.go
lib/attack.go
lib/targets.go

Some users of vegeta must be able to control how the request body is
sent. By default, the Go HTTP client doesn't make any guarantees about
which transfer encoding is used.
https://sourcegraph.com/github.com/golang/go/-/blob/src/net/http/request.go#L202
Fixes #439

attack: Implement the -chunked flag

---

README.md
lib/targets.go
lib/targets_test.go

Closes issue #447
Sometimes is nice to provide more information about a specific header, specially when sharing targets files. For this reason would be nice be able to put comments in the header section.

Fix comments between headers (#447)

---

scripts/load-ramping/README.md
scripts/load-ramping/ramp-requests.plt
scripts/load-ramping/ramp-requests.py

This script will automatically run vegeta against a target with different request rates and graph the latency distribution and success rate at each request rate.
This lets you see a couple interesting things that are less visible otherwise, e.g.:
* Multimodal latency distributions and outliers
* How performance degrades well _before_ the server starts dropping packets
The script is intentionally short (no cli options or abstraction layers etc) and excessively documented, so that people can easily adapt it to their needs.
I'm not sure if doing this as a separate script is ok for you. The original version of this was written in Go, using vegeta's API instead of JSON interface, with config as constants. But that wasn't very useable, especially without an already setup dev environment. I …

Add web server benchmarking script

---

attack.go
lib/attack.go

The connections option is misleading, as it let you think that no more
than the given number of connections will be established during the
attack, whereas it does only control the maximum amount of idle connection
in the pool, but keep the maximum number of connection unlimited.
The max-connection sets the maximum number of connections per target
host, which is what most people certainly expect the connections option
does.

Add the max-connections option

---

encode.go
lib/attack.go
lib/results.go
lib/results_easyjson.go
lib/results_test.go

Headers are written in wire format. CSV output uses base64 to encode
headers.
Fixes #303

Capture HTTP headers in results

---

lib/attack.go
lib/attack_test.go

Following up the discussion here https://github.com/tsenart/vegeta/issues/462
This adds the res.Seq to the target headers with the name "X-Vegeta-Seq".
This also add a new unit test to check that the header is equal to the res.Seq.

Add header to target containing the sequence number

---

lib/histogram.go
lib/histogram_test.go

Fixes #522
When reporting `hist` with buckets that doesn't start with 0, any requests that won't fit the first bucket will fall into the *last* bucket, skewing the results. Please see discussion in issue #522 . 
This PR will check if the first bucket starts with 0. If not, it will create a default bucket for such cases. For example, this input
`-hist[5ms,10ms,1s]` will generate the following buckets: `[0,5ms], [5ms,10ms], [10ms,1s], [1s,+Inf]` (and not `[5ms,10ms], [10ms,1s], [1s,+Inf]`)

Added default first hist bucket if needed

---

README.md

The default value of the `-timeout` flag in the README differs from the actual value of `30s`.

Update default -timeout value in README
